# Generated by Django 5.1.2 on 2024-12-08 10:37

import HelloMusicApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('measure_number', models.IntegerField()),
                ('time_signature', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tempo', models.CharField(blank=True, max_length=30, null=True)),
                ('key_signature', models.CharField(blank=True, max_length=30, null=True)),
                ('time_signature', models.CharField(blank=True, max_length=30, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSheetFolder',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('chord_symbol', models.CharField(max_length=30)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='HelloMusicApp.musicsheet'),
        ),
        migrations.AddField(
            model_name='musicsheet',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_sheets', to='HelloMusicApp.musicsheetfolder'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('pitch', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('tie', models.CharField(max_length=30)),
                ('accidental', models.CharField(max_length=30)),
                ('duration_value', models.DecimalField(decimal_places=5, max_digits=7)),
                ('dynamics', models.CharField(max_length=30)),
                ('articulation', models.CharField(max_length=30)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=HelloMusicApp.models.Profile.user_directory_path, validators=[HelloMusicApp.models.validate_image_format])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=30)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=50)),
                ('clef_type', models.CharField(max_length=50)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='HelloMusicApp.musicsheet')),
            ],
        ),
        migrations.CreateModel(
            name='UserMusicSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloMusicApp.musicsheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sheet', 'user')},
            },
        ),
        migrations.AddField(
            model_name='musicsheet',
            name='users',
            field=models.ManyToManyField(related_name='user_music_sheets', through='HelloMusicApp.UserMusicSheet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMusicSheetFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloMusicApp.musicsheetfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.AddField(
            model_name='musicsheetfolder',
            name='users',
            field=models.ManyToManyField(related_name='user_sheet_folders', through='HelloMusicApp.UserMusicSheetFolder', to=settings.AUTH_USER_MODEL),
        ),
    ]
