# Generated by Django 5.1.3 on 2024-11-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('measure_number', models.IntegerField()),
                ('time_signature', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tempo', models.CharField(max_length=30)),
                ('key_signature', models.CharField(max_length=30)),
                ('time_signature', models.CharField(max_length=30)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('chord_symbol', models.CharField(max_length=30)),
                ('measureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='sheetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='HelloMusicApp.musicsheet'),
        ),
        migrations.CreateModel(
            name='MusicSheetFolder',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musicsheet',
            name='folderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_sheets', to='HelloMusicApp.musicsheetfolder'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('pitch', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('tie', models.CharField(max_length=30)),
                ('accidental', models.CharField(max_length=30)),
                ('duration_value', models.DecimalField(decimal_places=5, max_digits=7)),
                ('dynamics', models.CharField(max_length=30)),
                ('articulation', models.CharField(max_length=30)),
                ('measureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('syllable_type', models.CharField(max_length=30)),
                ('noteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='HelloMusicApp.note')),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=30)),
                ('measureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='HelloMusicApp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=50)),
                ('clef_type', models.CharField(max_length=50)),
                ('sheetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='HelloMusicApp.musicsheet')),
            ],
        ),
        migrations.CreateModel(
            name='UserMusicSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloMusicApp.musicsheet')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musicsheet',
            name='users',
            field=models.ManyToManyField(related_name='music_sheets', through='HelloMusicApp.UserMusicSheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
