# Generated by Django 5.1.3 on 2024-11-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='folderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_sheets', to='HelloMusicApp.musicsheetfolder'),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='key_signature',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='tempo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='time_signature',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
