# Generated by Django 5.1.3 on 2024-11-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0003_rename_measureid_chord_measure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='music_sheets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermusicsheet',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='users',
            field=models.ManyToManyField(related_name='user_music_sheets', through='HelloMusicApp.UserMusicSheet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermusicsheet',
            unique_together={('sheet', 'user')},
        ),
        migrations.CreateModel(
            name='UserMusicSheetFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloMusicApp.musicsheetfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.AddField(
            model_name='musicsheetfolder',
            name='users',
            field=models.ManyToManyField(related_name='user_sheet_folders', through='HelloMusicApp.UserMusicSheetFolder', to=settings.AUTH_USER_MODEL),
        ),
    ]
