# Generated by Django 5.1.2 on 2024-12-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0003_musicsheet_clef_type_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('measure_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('music_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='HelloMusicApp.musicsheet')),
            ],
            options={
                'ordering': ['y_position', 'x_position'],
            },
        ),
    ]
