# Generated by Django 5.1.3 on 2024-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0004_musicsheet_owner_usermusicsheet_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicsheet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='musicsheetfolder',
            name='owner',
        ),
        migrations.AlterField(
            model_name='usermusicsheet',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermusicsheetfolder',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=50),
        ),
    ]
