# Generated by Django 5.1.3 on 2024-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0005_remove_musicsheet_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusicsheet',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermusicsheetfolder',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
