# Generated by Django 5.1.3 on 2024-12-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0005_remove_chord_chord_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='measure',
        ),
        migrations.AddField(
            model_name='chord',
            name='chord_symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ChordLibrary',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('chords', models.ManyToManyField(related_name='chords', to='HelloMusicApp.chord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_libraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
