# Generated by Django 5.1.3 on 2024-12-26 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0006_remove_chord_measure_chord_chord_symbol_chordlibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordlibrary',
            name='chords',
            field=models.ManyToManyField(blank=True, related_name='chords', to='HelloMusicApp.chord'),
        ),
        migrations.AlterField(
            model_name='chordlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
