# Generated by Django 5.1.2 on 2024-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloMusicApp', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
